using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Jukebox.API.Migrations
{
    /// <inheritdoc />
    public partial class PopulaNacionalidades : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('AFG', 'Afeganistão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ZAF', 'África do Sul')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ALA', 'Ilhas Alanda')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ALB', 'Albânia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('DEU', 'Alemanha')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('AND', 'Andorra')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('AGO', 'Angola')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('AIA', 'Anguilla')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ATA', 'Antárctida')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ATG', 'Antígua e Barbuda')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ANT', 'Antilhas Holandesas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SAU', 'Arábia Saudita')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('DZA', 'Argélia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ARG', 'Argentina')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ARM', 'Arménia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ABW', 'Aruba')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('AUS', 'Austrália')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('AUT', 'Austria')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('AZE', 'Azerbaijão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BHS', 'Bahamas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BHR', 'Bahrein')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BGD', 'Bangladesh')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BRB', 'Barbados')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BEL', 'Bélgica')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BLZ', 'Belize')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BEN', 'Benim')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BMU', 'Bermudas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BLR', 'Bielorrússia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BTN', 'Butão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BOL', 'Bolívia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BIH', 'Bósnia e Herzegovina')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BWA', 'Botsuana')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BVT', 'Ilha Bouvet')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BRA', 'Brasil')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BRN', 'Brunei')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BGR', 'Bulgária')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BFA', 'Burkina Faso')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BDI', 'Burundi')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('KHM', 'Camboja')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CMR', 'Camarões')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CAN', 'Canadá')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CPV', 'Cabo Verde')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CYM', 'Ilhas Cayman')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('KAZ', 'Cazaquistão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TCD', 'Chade')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CHL', 'Chile')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CHN', 'China')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CYP', 'Chipre')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CXR', 'Ilha Christmas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CCK', 'Ilhas Cocos')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('COL', 'Colômbia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('COM', 'Comores')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('COG', 'Congo')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('COK', 'Ilhas Cook')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PRK', 'Coreia do Norte')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('KOR', 'Coreia do Sul')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CRI', 'Costa Rica')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CIV', 'Costa do Marfim')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('HRV', 'Croácia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CUB', 'Cuba')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('DNK', 'Dinamarca')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('DJI', 'Djibouti')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('DMA', 'Dominica')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ECU', 'Equador')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('EGY', 'Egito')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SLV', 'El Salvador')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ARE', 'Emirados Árabes Unidos')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ERI', 'Eritreia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SCO', 'Escócia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SVK', 'Eslováquia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SVN', 'Eslovênia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ESP', 'Espanha')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('USA', 'Estados Unidos')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('UMI', 'Ilhas Menores Distantes dos Estados Unidos')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('EST', 'Estônia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ETH', 'Etiópia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('FRO', 'Ilhas Feroé')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('FJI', 'Fiji')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PHL', 'Filipinas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('FIN', 'Finlândia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('FRA', 'França')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ATF', 'Terras Austrais e Antárticas Francesas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GAB', 'Gabão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GHA', 'Gana')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GMB', 'Gâmbia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GEO', 'Geórgia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SGS', 'Ilhas Geórgia do Sul e Sandwich do Sul')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GIB', 'Gibraltar')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GRD', 'Granada')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GRC', 'Grécia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GRL', 'Gronelândia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GLP', 'Guadalupe')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GUM', 'Guam')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GTM', 'Guatemala')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GGY', 'Guernsey')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GIN', 'Guiné')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GNB', 'Guiné-Bissau')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GNQ', 'Guiné Equatorial')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GUY', 'Guiana')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GUF', 'Guiana Francesa')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('HTI', 'Haiti')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('HMD', 'Ilha Heard e Ilhas McDonald')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('HND', 'Honduras')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('HKG', 'Hong Kong')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('HUN', 'Hungria')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('YEM', 'Iémen')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('IND', 'Índia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('IDN', 'Indonésia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ENG', 'Inglaterra')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('IRN', 'Irã')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('IRQ', 'Iraque')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('IRL', 'Irlanda')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NIR', 'Irlanda do Norte')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('IMN', 'Ilha de Man')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ISL', 'Islândia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ISR', 'Israel')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ITA', 'Itália')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('JAM', 'Jamaica')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('JPN', 'Japão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('JEY', 'Jersey')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('JOR', 'Jordânia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('KIR', 'Kiribati')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('KWT', 'Kuwait')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LAO', 'Laos')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LVA', 'Letônia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LSO', 'Lesoto')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LBN', 'Líbano')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LBR', 'Libéria')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LBY', 'Líbia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LIE', 'Liechtenstein')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LTU', 'Lituânia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LUX', 'Luxemburgo')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MAC', 'Macau')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MKD', 'Macedónia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MDG', 'Madagáscar')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MYS', 'Malásia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MWI', 'Malaui')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MDV', 'Maldivas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MLI', 'Mali')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MLT', 'Malta')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('FLK', 'Ilhas Malvinas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MHL', 'Ilhas Marshall')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MNP', 'Marianas Setentrionais')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MAR', 'Marrocos')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MTQ', 'Martinica')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MRT', 'Mauritânia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MUS', 'Maurícia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MYT', 'Mayotte')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MEX', 'México')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MMR', 'Mianmar')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('FSM', 'Estados Federados da Micronésia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MDA', 'Moldávia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MCO', 'Mónaco')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MNG', 'Mongólia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MNE', 'Montenegro')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MSR', 'Montserrat')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MOZ', 'Moçambique')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NAM', 'Namíbia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NRU', 'Nauru')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NPL', 'Nepal')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NCL', 'Nova Caledônia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NZL', 'Nova Zelândia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NIC', 'Nicarágua')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NER', 'Níger')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NGA', 'Nigéria')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NIU', 'Niue')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NFK', 'Ilha Norfolk')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NOR', 'Noruega')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('OMN', 'Omã')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('WAL', 'País de Gales')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('NLD', 'Países Baixos')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PLW', 'Palau')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PSE', 'Palestina')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PAN', 'Panamá')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PNG', 'Papua-Nova Guiné')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PAK', 'Paquistão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PRY', 'Paraguai')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PER', 'Peru')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PCN', 'Pitcairn')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PYF', 'Polinésia Francesa')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('POL', 'Polónia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PRT', 'Portugal')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('PRI', 'Porto Rico')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('QAT', 'Qatar')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('KEN', 'Quênia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('KGZ', 'Quirguistão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('GBR', 'Reino Unido')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('IOT', 'Território Britânico do Oceano Índico')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('VGB', 'Ilhas Virgens Britânicas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CAF', 'República Centro-Africana')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CZE', 'República Checa')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('COD', 'República Democrática do Congo')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('DOM', 'República Dominicana')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TWN', 'Taiwan')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('REU', 'Reunião')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ROU', 'Romênia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('RUS', 'Rússia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('RWA', 'Ruanda')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ESH', 'Saara Ocidental')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SLB', 'Ilhas Salomão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('WSM', 'Samoa')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ASM', 'Samoa Americana')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('BLM', 'Saint-Barthélemy')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SHN', 'Santa Helena (território)')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LCA', 'Santa Lúcia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('MAF', 'Saint Martin')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('KNA', 'São Cristóvão e Névis')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SPM', 'São Pedro e Miquelão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('VCT', 'São Vicente e Granadinas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SMR', 'São Marinho')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('STP', 'São Tomé e Príncipe')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SEN', 'Senegal')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SLE', 'Serra Leoa')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SRB', 'Sérvia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SYC', 'Seychelles')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SGP', 'Singapura')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SYR', 'Síria')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SOM', 'Somália')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('LKA', 'Sri Lanka')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SDN', 'Sudão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SSD', 'Sudão do Sul')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SWE', 'Suécia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SWZ', 'Suazilândia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('CHE', 'Suíça')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SUR', 'Suriname')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('SJM', 'Svalbard')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TJK', 'Tadjiquistão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('THA', 'Tailândia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TZA', 'Tanzânia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TLS', 'Timor-Leste')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TGO', 'Togo')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TKL', 'Toquela')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TON', 'Tonga')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TTO', 'Trinidad e Tobago')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TUN', 'Tunísia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TKM', 'Turcomenistão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TUR', 'Turquia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TCA', 'Turcas e Caicos')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('TUV', 'Tuvalu')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('UKR', 'Ucrânia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('UGA', 'Uganda')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('VIR', 'Ilhas Virgens Americanas')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('URY', 'Uruguai')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('UZB', 'Uzbequistão')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('VUT', 'Vanuatu')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('VAT', 'Vaticano')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('VEN', 'Venezuela')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('VNM', 'Vietname')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('WLF', 'Wallis e Futuna')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ZMB', 'Zâmbia')");
            migrationBuilder.Sql("Insert Into Nacionalidades(Sigla, Nome) Values('ZWE', 'Zimbábue')");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("Delete From Nacionalidades");
        }
    }
}
